# Generated by Django 3.0.3 on 2020-02-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('apellidoPaterno', models.TextField()),
                ('apellidoMaterno', models.TextField(null=True)),
            ],
        ),
    ]
