# Generated by Django 3.0.3 on 2020-02-24 07:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='id',
        ),
        migrations.AddField(
            model_name='clientes',
            name='cliente_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Id Unico de Cliente', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='clientes',
            name='correo',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('cuenta_id', models.UUIDField(default=uuid.uuid4, help_text='Id Unico de Cuenta', primary_key=True, serialize=False)),
                ('numero_tarjeta', models.PositiveIntegerField(default=0)),
                ('saldo', models.PositiveIntegerField(default=0)),
                ('cliente', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banco.Clientes')),
            ],
        ),
    ]
