# Generated by Django 3.0.3 on 2020-02-24 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0003_auto_20200224_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transaccion', models.TextField()),
                ('monto', models.SmallIntegerField()),
                ('cuenta', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='banco.Cuenta')),
            ],
        ),
    ]
