# Generated by Django 3.0.3 on 2020-02-28 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0005_auto_20200227_2010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cuenta',
            new_name='Cuentas',
        ),
    ]
