# Generated by Django 3.0.3 on 2020-03-06 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0009_auto_20200305_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentas',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='banco.Clientes'),
        ),
        migrations.AlterField(
            model_name='cuentas',
            name='saldo',
            field=models.CharField(max_length=10),
        ),
    ]
